
API_KEY = "47abd6fca9faad069da778f0cdbb0b9c"
BASE_URL = "http://api.openweathermap.org/data/2.5/weather?"

HEADER_TOP_TEXT_SIZE = 20 
HEADER_TOP_TEXT_COLOR = "#000000"  
HEADER_TEXT_TOP_BORDER_THICKNESS = 2.5


SEARCH_BAR_BORDER_COLOR = "#FFFFFF"
SEARCH_BUTTON_COLOR = "#0068E5"
SEARCH_BUTTON_TEXT_COLOR = "#FFFFFF"


DEFAULT_BACKGROUND_IMAGE = "assets/background.png"
SEARCH_ICON_IMAGE = "assets/search_icon.png"


INFO_TEXT_COLOR = "#000000"
INFO_BORDER_THICKNESS = 3


DEFAULT_CITY = "New Delhi"
